name: pyos-metrics
channels:
  - conda-forge
dependencies:
  - python=3.13
  - jupyterlab
  - jupyterlab_code_formatter
  - jupyterlab-myst
  - black
  - isort
  - pip
  - mystmd
  - pyarrow
  - pandas
  - altair
  - itables
  - plotly
  - pip:
    - pyosmeta
  #   - jupyterlab_code_formatter[isort]
