---
title: Welcome to pyOpenSci Metrics Dashboards
jupyter: python3
execute:
  echo: false
---

```{python}
from datetime import datetime

today = datetime.today().date().strftime("%d %B %Y")
```

*Last updated: **`{python} today`***

Dashboards for pyOpenSci peer review, packages, and community activity.
To contribute, see the [README](https://www.github.com/pyopensci/metrics/README.md).

::: {.grid}

::: {.g-col-12 .g-col-md-4 style="border: 1px solid #cccccc; padding: 10px"}

**Peer review**

* [Peer review status dashboard](/peer-review/peer-review-status-dashboard.html)
* [Editorial dashboard](/peer-review/editorial-dashboard.html)
* [Current review status](/peer-review/current-review-status.html)
* [Reviews over time](/peer-review/reviews-over-time.html)
* [Peer review trends](/peer-review/review-trends.html)

:::

::: {.g-col-12 .g-col-md-4 style="border: 1px solid #cccccc; padding: 10px"}

**Package metrics**

* [Accepted package metrics](/peer-review/accepted-packages.html)
* [Package dashboard](/peer-review/pyos-package-dashboard.html)
* [Package activity](/pyos-packages/package-activity.html)

:::

::: {.g-col-12 .g-col-md-4 style="border: 1px solid #cccccc; padding: 10px"}

**Contributors**

* [Contributor data](/contributors/contributors.html)
* [Sprint data](/contributors/sprints.html)

:::

:::
