version: 2.1

jobs:
  build-website:  # Renamed the job to build-website
    docker:
      - image: cimg/python:3.11  # Primary image with Python
      - image: cimg/node:22.0    # Secondary image with Node.js 22.x

    steps:
      - checkout
      - run:
          name: setup environment
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip list
      - run:
          name: setup Node.js environment
          command: |
            node -v  # Verify Node.js version
            npm install  # Install Node.js dependencies if needed
      - run:
          name: Build website HTML
          command: nox -s html

      - store_artifacts:
          path: _build/html
          destination: html

# Define the workflow
workflows:
  version: 2
  build-website:  # Updated the workflow name to match the job name
    jobs:
      - build-website
